version: '3.1'

services:
  dbconsole:
    image: hub.coloseo.io/adminer
    ports:
      - "8082:8080"
  db:
    image: hub.coloseo.io/mysql:5.7
    volumes:
      - .data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=baggio
      - MYSQL_USER=baggio
      - MYSQL_PASSWORD=baggio
      - MYSQL_DATABASE=baggio
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
